# Generated by Django 4.0.4 on 2022-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(verbose_name='Launching mailing')),
                ('date_end', models.DateTimeField(verbose_name='Ending mailing')),
                ('time_start', models.TimeField(verbose_name='Sending time')),
                ('time_end', models.TimeField(verbose_name='The end time of sending')),
                ('text', models.TextField(max_length=255, verbose_name='Message text')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Tag')),
                ('mobile_operator_code', models.CharField(blank=True, max_length=3, verbose_name='Mobile operator code')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
    ]
